### PR TITLE
Upgrade intl to 0.19.0 AND gradle from 4.2.2 to 7.4.2

### LINKED ISSUE #90: [General]: Incompatible with Flutter 3.22 due to dependency on intl 0.18.1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.1

### Platforms

- [X] Android
- [X] iOS
- [X] Linux
- [X] MacOS
- [X] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```yml
dependencies:
    form_builder_validators: ^9.1.0 
```

</details>

### Current Behavior

Version solving failed
```bash
flutter pub get
Resolving dependencies... 
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0 and <package> depends on intl ^0.18.1, flutter_localizations from sdk is forbidden.
So, because <package> depends on flutter_localizations from sdk, version solving failed.
```

### Expected Behavior

Version solving possible

### Steps To Reproduce

1. Update flutter to 3.22
2. Add form_builder_validators: ^9.1.0 to `pubspec.yml`
3. run `flutter pub get`

### Aditional information

_No response_

### LINKED ISSUE #91: Because every version of form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.19.0, every version of form_builder_validators requires intl 0.19.0.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1.1.1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

nothing

### Minimal code example

nothing

### Current Behavior

nothing

### Expected Behavior

nothing

### Steps To Reproduce

nothing

### Aditional information

_No response_

### LINKED ISSUE #92: Update form_builder_validators to intl ^0.19.0 package
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Versi¢n 10.0.22631.3527], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[√] Android Studio (version 2023.2)
[√] VS Code, 64-bit edition (version 1.89.1)
[√] Connected device (1 available)
[√] Network resources
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
flutter pub update
```

</details>

### Current Behavior

flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required
form_builder_validators ^9.1.0, version solving failed because dependes on intl ^0.18.0

### Expected Behavior

flutter pub update updates to latest packaged using intl 0.19.0

### Steps To Reproduce

flutter pub update

### Aditional information

_No response_

### PR DESCRIPTION
**Pull request by jhaglund**
## Connection with issue(s)

Close #90  
Close #91 
Close #92 
Close #93  

Connected to #???

## Solution description

(updated May 17 to try to be more clear)
You're welcome to replicate the steps I did. The only "manual" edit I did was to change the 18 to 19, otherwise the changes were all made by the Android Studio tools.

The key is instead of opening the Flutter project, you open the /example/android directory with Android Studio then use the AGP upgrade assistant (under tools) to upgrade gradle. Maybe VS code can do it but IDK. Sorry I made so many commits, this process gets sticky so I was cribbing my progress.

Thanks!

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by deandreamatias** [comment]
Also need update the minimum flutter and dart version to avoid conflicts with old versions

```yaml
environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"
```

**Comment by samuelyung** [comment]
@deandreamatias When can it be merged, please?

**Comment by enchance** [comment]
When will this be merged?

**Comment by listepo** [comment]
pls merge

**Comment by ozayr** [comment]
any idea when this will merge?

**Comment by martijn00** [comment]
https://github.com/flutter-form-builder-ecosystem/form_builder_validators/pull/88 this pr should also be included in this major update to the dependencies

**Comment by deandreamatias** [comment]
Sorry, I don't have time to check build errors but I also don't want to get the MR approved without the build working properly.
If someone can solve it, I will approve it on the same day.

**Comment by jhaglund** [comment]
I'll be honest, the various Java environment and tool versions confuse me.

The error says to run `flutter doctor --version` to find the Java version. Mine returns `Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)` but IDK how to check what the build server is using.

It provides this link to explain java and gradle compatibility: https://docs.gradle.org/current/userguide/compatibility.html#java But to me, it is unclear what Java versions the even numbered gradle versions are compatible with (who is reverse compatible with who?).

Anyway, I ran the AGP upgrade again, bringing the Gradle plugin to the latest, 8.3.1 (but also, it says 8.4 in places), and it still builds for me. I didn't upgrade to the latest before because 7.4 was where I got it to build on my machine. 

I hope this helps!

**Comment by martijn00** [comment]
@jhaglund I'll get to this soon and update my PR to fix the build system and dependencies.

**Comment by deandreamatias** [comment]
Olee it's solved! Thanks a lot for all to accomplish this

**Comment by samuelyung** [comment]
@deandreamatias When will publish a release to pub?

**Comment by martijn00** [comment]
I'll update my PR today and will set everything ready. It's better to do it all in the 1 major update.

**Comment by martijn00** [comment]
@samuelyung @deandreamatias my PR is updated now.

**Comment by WasimMemon** [comment]
Is this build updated on pub dev ?
I am getting same error after upgrading to 9.1.0
I have upgraded flutter version also.

**Comment by martijn00** [comment]
No, my PR is not merged yet and there is no new tag set on the repo.

**Comment by jhaglund** [comment]
> Is this build updated on pub dev ? I am getting same error after upgrading to 9.1.0 I have upgraded flutter version also.

As a temporary workaround, you can edit your pubspec.yaml to point to the github instead of pub.dev

```
#form_builder_validators: ^9.0.0
  form_builder_validators:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/form_builder_validators.git
      ref: main # branch name


```

**Comment by deandreamatias** [comment]
> I don't understand why this kind of critical hotfix needs to wait to publish. This package simply is unusable without this fix. No, the reality is that any project which depends on this package instantly becomes unbuildable. This fix should be publish to pub ASAP IMO.

Because this is a open source package and I work for free in this project.
I need spent my time in my main job to pay my bills. Neither Google, Flutter nor any other company pays me to work on this.

I am open and encourage anyone to participate in the flutter-form-builder-ecosystem

**Comment by deandreamatias** [comment]
Version 10.0.0 with fix, deployed https://pub.dev/packages/form_builder_validators

**Pull request merged**
