### PR TITLE
Use `flutter gen-l10n` to generate `FormBuilderLocalizations`

### LINKED ISSUE #20: Change default error arabic Text message
I want to change this text to my custom text in all form builder validators in the app.

Screen Shot 2022-10-20 at 10 40 00 AM

### PR DESCRIPTION
**Pull request by ipcjs**
## Connection with issue(s)

1. #20 
2. #8 
3. #4 

Close #20 #4 #8 

## Solution description

Using gen-10n, users of the library can easily modify and add new languages.

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by deandreamatias** [comment]
Hi @ipcjs 
Thanks a lot for your contribution!
I will need two things to review better this package:

1. Review a package size before and after this change. Can use https://docs.flutter.dev/perf/app-size#breaking-down-the-size
2. Update documentation for [use package](https://github.com/flutter-form-builder-ecosystem/form_builder_validators#setup) and how [add new language](https://github.com/flutter-form-builder-ecosystem/form_builder_validators#add-new-supported-language)
3. Remove folder `lib/localization/intl/` for lint analysis

**Comment by ipcjs** [comment]
exec `flutter build apk --target-platform=android-arm64 --analyze-size` in `example`

image

**Comment by ipcjs** [comment]
I updated the documentation.

In terms of l10n, I have tried to maintain compatibility and there is basically no difference in usage.

**Comment by deandreamatias** [comment]
> exec `flutter build apk --target-platform=android-arm64 --analyze-size` in `example`
> 
> image

If I understand correctly, with this PR the package will be **lower** size? Really awesome!

**Pull request merged**
