### PR TITLE
Add some features and more tests

### PR DESCRIPTION
**Pull request by martijn00**
## Solution description

I've added a bunch of tests. There are some issues with null checks etc that should be fixed.

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [x] Add unit test to verify new or fixed behaviour
- [x] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by deandreamatias** [comment]
Maybe in this MR can add the think that I commented here https://github.com/flutter-form-builder-ecosystem/form_builder_validators/pull/101#pullrequestreview-2079579665

Validate a lot the all validators, is something important before publish a new version

**Comment by martijn00** [comment]
@deandreamatias I can look into faker_dart but for now would first like to implement the current tests and get a release out. Are you adding it in #104 ?

**Comment by deandreamatias** [comment]
We can add the two things.
My idea is implementing in #104

**Comment by martijn00** [comment]
@deandreamatias I've done a couple of fixes but one thing i notice is inconsistency in handling `null` and `''` string checks. In general should a empty string or null value pass a validation? I would think not? But in all the older code it does.

What is your opinion?

**Comment by martijn00** [comment]
@deandreamatias This one is finished now. I would prefer to refactor the inconsistency in handling `null` and `''` and bump the whole release to a v11 with the breaking changes. If that is ok for you i'll make a new PR for that.

**Review by deandreamatias — CHANGES_REQUESTED** [review]
You can define [macro templates](https://github.com/dart-lang/dartdoc#macros) for regex (lib/src/utils/validators.dart) and add to validator dart doc to give more context

Example:
```dart
/// {@template hex_template}
/// This regex match with
/// 
/// - Starts with a # character.
/// - Is followed by exactly six characters, each of which is a hexadecimal digit (0-9, a-f, or A-f).
/// - Has no additional characters before or after this pattern.
/// 
/// Examples: #1a2b3c and #ABCDEF
/// {@endtemplate}
RegExp _hex = RegExp(r'^#[0-9a-fA-F]{6}$')
```

```dart
/// {@macro hex_template}
static FormFieldValidator<String> colorCode({
```

**Comment by deandreamatias** [comment]
@martijn00 I don't know if empty string or null should be pass on validation. Maybe not.
I will take a look on code to understand better this behavior

**Comment by deandreamatias** [comment]
Remember to use the macro on validators
 ```dart
 /// {@macro hex_template}
 static FormFieldValidator<String> colorCode({
 ```

**Comment by martijn00** [comment]
@deandreamatias thanks! I'll have a look at the null checks next. In general I think the behaviour should be that if a value is null or empty it should show the error message, right?

**Pull request merged**
