### PR TITLE
build(deps): bump intl from 0.18.1 to 0.19.0

### LINKED ISSUE #90: [General]: Incompatible with Flutter 3.22 due to dependency on intl 0.18.1
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.1

### Platforms

- [X] Android
- [X] iOS
- [X] Linux
- [X] MacOS
- [X] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```yml
dependencies:
    form_builder_validators: ^9.1.0 
```

</details>

### Current Behavior

Version solving failed
```bash
flutter pub get
Resolving dependencies... 
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0 and <package> depends on intl ^0.18.1, flutter_localizations from sdk is forbidden.
So, because <package> depends on flutter_localizations from sdk, version solving failed.
```

### Expected Behavior

Version solving possible

### Steps To Reproduce

1. Update flutter to 3.22
2. Add form_builder_validators: ^9.1.0 to `pubspec.yml`
3. run `flutter pub get`

### Aditional information

_No response_

### LINKED ISSUE #91: Because every version of form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.19.0, every version of form_builder_validators requires intl 0.19.0.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1.1.1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

nothing

### Minimal code example

nothing

### Current Behavior

nothing

### Expected Behavior

nothing

### Steps To Reproduce

nothing

### Aditional information

_No response_

### LINKED ISSUE #92: Update form_builder_validators to intl ^0.19.0 package
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Versi¢n 10.0.22631.3527], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[√] Android Studio (version 2023.2)
[√] VS Code, 64-bit edition (version 1.89.1)
[√] Connected device (1 available)
[√] Network resources
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
flutter pub update
```

</details>

### Current Behavior

flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required
form_builder_validators ^9.1.0, version solving failed because dependes on intl ^0.18.0

### Expected Behavior

flutter pub update updates to latest packaged using intl 0.19.0

### Steps To Reproduce

flutter pub update

### Aditional information

_No response_

### PR DESCRIPTION
**Pull request by kNoAPP**
## Connection with issue(s)

Close #92
Close #91
Close #90

## Solution description
Upgrades the intl package to 0.19.0 so that Flutter SDK v3.22.0 is supported.

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Review by deandreamatias — CHANGES_REQUESTED** [review]
Need increase the flutter and dart minimum version, to avoid conflict with old version off Flutter

**Comment by NinoBass** [comment]
How soon can this be merged please? @deandreamatias

**Review by deandreamatias — APPROVED** [review]

**Comment by deandreamatias** [comment]
Had some error that isn't related to the intl dependency but with increase flutter version (I guess).
https://github.com/flutter-form-builder-ecosystem/form_builder_validators/actions/runs/9104136037/job/25067818196?pr=93

Take a look if can solve

**Comment by roskakori** [comment]
@deandreamatias It seems the project is using gradle 6.7. When running a `flotter create xxx` with the current Flutter 3.22, it uses gradle 7.6.3.

Possibly upgrading the gradle included in the project fixes this. You can try the instructions at [Android Java Gradle migration guide](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide) which would come down to:
```bash
cd android
./gradlew wrapper --gradle-version=7.6.3
```
My personal experience with upgrading gradle in an existing Flutter project has been sketchy. What eventually fixed it for me was to
```
cd /tmp
flutter create form_builder_validators
```
and then just copy the `/tmp/form_builder_validators/android` folder over the existing project's `android` folder. If you previously modified any files in the project's `android` folder (e.g. adding properties), you will need to repeat these modifications.

**Pull request closed without merging**
