### PR TITLE
Update the intl to it's latest version

### PR DESCRIPTION
**Pull request by ArbazIrshad**
Update `intl` to it's latest version as it was causing dependency issue with several packages.

### CODE REVIEW

**Comment by deandreamatias** [comment]
Hi @ArbazIrshad 
Thanks for contribution, but I don't update this dependency because the flutter_localizations don't update the intl version, so throw this error:

```shell
Running "flutter pub get" in form_builder_validators...
Resolving dependencies...
Because form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because form_builder_validators depends on intl ^0.18.0, version solving failed.
pub get failed
```

Only when release a new stable Flutter version than we can merge this PR

**Comment by CGrandez** [comment]
flutter already updated the intl dependency.

**Comment by shilangyu** [comment]
New flutter stable version is releases, and this intl bump is needed. Then of course a similar bump has to be done in https://github.com/flutter-form-builder-ecosystem/flutter_form_builder.

**Comment by danielroek** [comment]
Fixed this same issue in #50 where I did update the minimum Flutter version to 3.10.0

**Comment by Panca6** [comment]
same problem here needed bump otherwise downgrade flutter back to 3.7.12

**Comment by deandreamatias** [comment]
This was done by #50

**Pull request closed without merging**
