### PR TITLE
Update CI

### LINKED ISSUE #79: Bulgarian language support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### What you'd like to happen

```Markdown
Bulgarian language support
```

### Alternatives you've considered

```Markdown
{
   "@@locale": "en",
   "creditCardErrorText": "Това поле изисква валиден номер на кредитна карта.",
   "dateStringErrorText": "Това поле изисква валиден низ за дата.",
   "emailErrorText": "Това поле изисква валиден имейл адрес.",
   "equalErrorText": "Стойността на това поле трябва да е равна на {value}.",
   "equalLengthErrorText": "Стойността трябва да има дължина, равна на {length}",
   "integerErrorText": "Това поле изисква валидно цяло число.",
   "ipErrorText": "Това поле изисква валиден IP.",
   "matchErrorText": "Стойността не съответства на модела.",
   "maxErrorText": "Стойността трябва да е по-малка или равна на {max}",
   "maxLengthErrorText": "Стойността трябва да има дължина, по-малка или равна на {maxLength}",
   "maxWordsCountErrorText": "Стойността трябва да има брой думи, по-малък или равен на {maxWordsCount}",
   "minErrorText": "Стойността трябва да е по-голяма или равна на {min}",
   "minLengthErrorText": "Стойността трябва да има дължина, по-голяма или равна на {minLength}",
   "minWordsCountErrorText": "Стойността трябва да има брой думи, по-голям или равен на {minWordsCount}",
   "notEqualErrorText": "Стойността на това поле не трябва да е равна на {value}.",
   "numericErrorText": "Стойността трябва да е числова.",
   "requiredErrorText": "Това поле не може да бъде празно.",
   "urlErrorText": "Това поле изисква валиден URL адрес."
}
```

### Aditional information

Please add it. Thanks!

### LINKED ISSUE #97: Error reading 'form_builder_validators-10.0.0/lib/localization/intl/messages.dart': No such file or directory
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

10.0.0

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart

```

</details>

### Current Behavior

It appears the lib/localization/intl/ directory got deleted, at least it's broken for me. I'll see if I can restore and send a pull request but maybe [martijn00](https://github.com/flutter-form-builder-ecosystem/form_builder_validators/commits?author=martijn00) can help?

There are also a bunch of errors related to `FormBuilderLocalizationsImpl` not found/not a type.

```
lib/override_form_builder_localizations_en.dart:7:13: Error: Type 'FormBuilderLocalizationsImplEn' not found.
    extends FormBuilderLocalizationsImplEn {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:10:38: Error: Type 'FormBuilderLocalizationsImpl' not found.
  static const LocalizationsDelegate<FormBuilderLocalizationsImpl> delegate =
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:21:35: Error: Type 'FormBuilderLocalizationsImpl' not found.
    extends LocalizationsDelegate<FormBuilderLocalizationsImpl> {
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:25:10: Error: Type 'FormBuilderLocalizationsImpl' not found.
  Future<FormBuilderLocalizationsImpl> load(Locale locale) {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:10:38: Error: 'FormBuilderLocalizationsImpl' isn't a type.
  static const LocalizationsDelegate<FormBuilderLocalizationsImpl> delegate =
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:29:30: Error: 'FormBuilderLocalizationsImpl' isn't a type.
    return SynchronousFuture<FormBuilderLocalizationsImpl>(instance);
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/localization/l10n.dart:14:10: Error: Type 'FormBuilderLocalizationsImpl' not found.
  static FormBuilderLocalizationsImpl of(BuildContext context) {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### Expected Behavior

errors shouldn't appear when I upgrade

### Steps To Reproduce

upgrade to 10.0.0, build a project

### Aditional information

_No response_

### PR DESCRIPTION
**Pull request by martijn00**
## Connection with issue(s)

Close #98 
Close #97
Close #79 
Close #80 

## Solution description

Tries to fix the problem with the build.

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [x] Add unit test to verify new or fixed behaviour
- [x] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by deandreamatias** [comment]
Take a look on this docs about gitignore and pubignore
https://dart.dev/tools/pub/publishing#what-files-are-published

**Comment by deandreamatias** [comment]
I think that need update the .gitignore with all stuff and **/intl and on .pubignore, all stuff but without the **/intl

**Comment by martijn00** [comment]
@deandreamatias thanks that did the trick. Should the example app be included or ignored as well?

Otherwise this PR is good to go.

**Comment by deandreamatias** [comment]
I would not add a validator in this PR, I would do it in another one as they are different things.

I think that the example can maintain the same setup that had

**Comment by martijn00** [comment]
@deandreamatias Alright, fixed that. I'll open a new PR for it.

**Pull request merged**
