### PR TITLE
Bump intl to 0.18.0

### PR DESCRIPTION
**Pull request by danielroek**
## Connection with issue(s)

Close #???

Connected to #???

## Solution description
Bumps version of intl to 0.18.0 to support Flutter 3.10.0

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [ ] Check the original issue to confirm it is fully satisfied
- [ ] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [ ] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Comment by danielroek** [comment]
CI fails due to issues with GitHub Actions, if [Github Status](https://www.githubstatus.com/) indicates Actions is working again, please retry the CI steps

**Comment by danielroek** [comment]
I see the workflow fails on using flutter commands instead of dart, I’ll update this PR in a bit

**Comment by danielroek** [comment]
@deandreamatias PR has been updated, unless I'm missing something the CI should work now

**Comment by deandreamatias** [comment]
When pass pipeline I will merge.
For next time, don't need change the version and changelog, I handle this but thanks for do it.

**Pull request merged**
